# Generated by Django 2.0.1 on 2018-01-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180108_1334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City1',
            new_name='CityDict',
        ),
    ]
