# Generated by Django 2.0.1 on 2018-01-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAsk',
        ),
    ]
