# Generated by Django 2.0.1 on 2018-01-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
    ]
